services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGODB_URI
        sync: false
